name = "binary_map"
description = "A map data structure stored in binary tree format"
version = "0.1.0-dev"

authors = ["Jean-Pierre Rosen"]
maintainers = ["Jean-Pierre Rosen <rosen@adalog.fr>"]
maintainers-logins = ["jprosen"]
licenses = "GPL-2.0-or-later"
website = "https://adalog.fr/en/components.html"
tags = ["map", "binary-tree", "key-value", "dictionary", "data-structure"]
